config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "lists#index"

  resources :lists, only: [:index, :new, :show, :create, :update] do
    resources :bookmarks, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

  # resources :movies, only: [:index, :show]
  resources :bookmarks, only: [:destroy]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "should happen once per list" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (1..5)}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :comments, dependent: :destroy
  has_one_attached :thumbnail

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.new(bookmark_params)
    if @bookmark.save
      redirect_to @list, notice: 'Movie was successfully added to the list.'
    else
      @movies = Movie.all
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @comment = @list.comments.build(comment_params)

    if @comment.save
      @comment = Comment.new
      redirect_to list_path(@list, anchor: 'comments_section')
    else
      redirect_to list_path(@list), alert: 'There was an error creating the comment.'
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @comment = @list.comments.find(params[:id])
    @comment.delete
    redirect_to list_path(@list)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :rating)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all.order(:name)
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
    @bookmark = @list.bookmarks
    @comment = Comment.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render :edit
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :thumbnail)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <div class="form-group">
    <%= f.input :movie_id, collection: @movies, label: 'Select a movie', prompt: 'Choose a movie' %>
  </div>

  <div class="form-group">
    <%= f.input :comment %>
  </div>

  <div class="actions">
    <%= f.button :submit, 'Add Movie', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/:create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid justify-content-between">
        <span class="navbar-brand">Movie Radar</span>
        <div class="navbar-nav">
          <%= link_to "My lists", lists_path, class: "nav-link" %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_modal.html.erb
<div class="modal" id="exampleModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Create your list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(list) do |f|  %>
          <%= f.input :name %>
          <%= f.input :thumbnail, as: :file %>
          <%= f.submit %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/lists/create.html.erb
<h1>The create page</h1>

app/views/lists/index.html.erb
<header class="container-fluid hero-banner justify-content-center align-items-center", style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(<%= asset_path 'cinema_hero.jpg' %>)">
  <h1>All your movies in one place</h1>
</header>

<div class="container my-4">
  <div class="d-flex justify-content-between mb-5">
    <h2>My Lists</h2>
    <%= render 'lists/modal', list: @list %>
    <button type="button" class="btn btn-success text-white" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Create New List
    </button>
  </div>
<div class="row gap-4 justify-content-evenly">
    <% @lists.each do |list| %>
      <% if list.thumbnail.attached? %>
        <% bg_image_url = cl_image_path(list.thumbnail.key) %>
        <%= link_to list_path(list), class: "my-button col-2 d-flex rounded justify-content-center align-items-center mr-3 text-white", style: "background-image: url('#{bg_image_url}');" do %>
          <h3 class="my-2"><%= list.name %></h3>
        <% end %>
      <% else %>
        <%= link_to list_path(list), class: "my-button col-8 d-flex rounded justify-content-center align-items-center mr-3 text-white" do %>
          <h3 class="my-2"><%= list.name %></h3>
        <% end %>
      <% end %>
    <% end %>
  </div>


</div>

app/views/lists/new.html.erb
<div class="container">

<h1>Create your list</h1>

<%= simple_form_for(@list) do |f|  %>
<%= f.input :name %>
<%= f.submit %>
<% end %>

<%= link_to "Go back", lists_path %>

</div>

app/views/lists/show.html.erb
<% if @list.thumbnail.key? %>
  <header class="container-fluid hero-banner justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(<%= cl_image_path(@list.thumbnail.key) %>)">
    <h1><%= @list.name %></h1>
  </header>
<% else %>
  <header class="container-fluid hero-banner justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5))">
    <h1><%= @list.name %></h1>
  </header>
<% end %>

<%# MODAL FOR THUMBNAIL %>
<div class="modal" id="thumbnailModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Create your list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@list) do |f|  %>
          <%= f.input :thumbnail, as: :file %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<button class="btn btn-success banner-button", data-bs-toggle="modal" data-bs-target="#thumbnailModal">Change Header</button>

<div class="container">
  <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-success" %>
  <div class="row my-3">
        <% @list.bookmarks.each do |item|  %>
          <div class="col-md-4 mb-4">
            <div class="card h-100 bg-white shadow">
              <img src="<%= item.movie.poster_url %>" class="card-img-top" alt="movie poster">
              <div class="card-body d-flex justify-content-between flex-column gap-4">
                <div>
                  <h5 class="card-title"><%= item.movie.title %></h5>
                  <p class="card-text"><%= item.movie.overview %></p>
                </div>
                <div>
                  <i class="fa-solid fa-star" style="color: #FFD43B;"></i>
                  <span><%= item.movie.rating %>/10</span>
                  <%= link_to "Delete", bookmark_path(item) ,data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
                  <div class="card-footer mt-2">
                    <p>"<%= item.comment %>"</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
  </div>

<hr>

  <h2 id="comments_section">Comments</h2>
  <div class="row">

  <div class="col-6">
    <% @list.comments.reverse_each do |comment| %>
    <div class="comment gap-2 p-2 mb-2">
      <% rating_count = comment.rating %>
        <% if rating_count.present? %>
          <% rating_count.times do %>
            <span class="star selected">★</span>
          <% end %>
        <% end %>
      <div class="d-flex justify-content-between">
        <p><%= comment.content %></p>
        <%= link_to "", list_comment_path(@list, comment), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn-close" %>
      </div>
    </div>
    <hr class="hr">
    <% end %>
  </div>

  <div class="col-6 border rounded p-4 bg-white shadow">
    <%= simple_form_for([@list, @comment]) do |f| %>
      <div class="form-group">
        <%= f.input :content, as: :text, label: "Add a comment", input_html: { class: 'form-control' } %>
      </div>

      <div class="form-group rating">
        <label>Rating</label>
        <div class="star-rating">
          <span class="star" data-value="1">&#9733;</span>
          <span class="star" data-value="2">&#9733;</span>
          <span class="star" data-value="3">&#9733;</span>
          <span class="star" data-value="4">&#9733;</span>
          <span class="star" data-value="5">&#9733;</span>
        </div>
        <%= f.hidden_field :rating, id: 'rating-input' %>
      </div>

      <div class="form-group">
        <%= f.button :submit, "Post Comment", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
  </div>

  <%= link_to "Go back", lists_path, class: "text-decoration-underline py-3 fs-6" %>
</div>